-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customer_contact
(
    id integer NOT NULL DEFAULT nextval('"customerContact_id_seq"'::regclass),
    phone character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    website character varying COLLATE pg_catalog."default",
    address character varying COLLATE pg_catalog."default",
    city character varying COLLATE pg_catalog."default",
    district character varying COLLATE pg_catalog."default",
    CONSTRAINT "customerContact_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer_enterprise
(
    id serial NOT NULL,
    business_name character varying COLLATE pg_catalog."default",
    founding_date timestamp with time zone,
    field character varying COLLATE pg_catalog."default",
    annual_revenue character varying COLLATE pg_catalog."default",
    employee_size character varying COLLATE pg_catalog."default",
    note character varying COLLATE pg_catalog."default",
    attachment_path character varying COLLATE pg_catalog."default",
    customer_contact serial NOT NULL,
    product serial NOT NULL,
    customer_lead serial NOT NULL,
    customer_type integer,
    assigned_staff integer,
    source character varying COLLATE pg_catalog."default",
    CONSTRAINT customer_enterprise_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer_lead
(
    id serial NOT NULL,
    full_name character varying COLLATE pg_catalog."default",
    "position" character varying COLLATE pg_catalog."default",
    phone character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    date_of_birth character varying COLLATE pg_catalog."default",
    note character varying COLLATE pg_catalog."default",
    CONSTRAINT customer_lead_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_interest
(
    id serial NOT NULL,
    category character varying COLLATE pg_catalog."default",
    productname character varying COLLATE pg_catalog."default",
    interest_status character varying COLLATE pg_catalog."default",
    interest_start_date character varying COLLATE pg_catalog."default",
    note text COLLATE pg_catalog."default",
    CONSTRAINT product_interest_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.customer_enterprise
    ADD CONSTRAINT fk_customer_contact FOREIGN KEY (customer_contact)
    REFERENCES public.customer_contact (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer_enterprise
    ADD CONSTRAINT fk_customer_lead FOREIGN KEY (customer_lead)
    REFERENCES public.customer_lead (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer_enterprise
    ADD CONSTRAINT fk_product FOREIGN KEY (product)
    REFERENCES public.product_interest (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;