-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customer_contact
(
    id bigint NOT NULL DEFAULT nextval('"customerContact_id_seq"'::regclass),
    phone character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    website character varying(255) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default",
    city character varying(255) COLLATE pg_catalog."default",
    district character varying(255) COLLATE pg_catalog."default",
    code character varying COLLATE pg_catalog."default",
    CONSTRAINT "customerContact_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer_enterprise
(
    id bigserial NOT NULL,
    business_name character varying(255) COLLATE pg_catalog."default",
    founding_date timestamp with time zone,
    field character varying(255) COLLATE pg_catalog."default",
    annual_revenue character varying(255) COLLATE pg_catalog."default",
    note character varying(255) COLLATE pg_catalog."default",
    attachment_path character varying(255) COLLATE pg_catalog."default",
    customer_contact serial,
    product serial,
    customer_lead serial,
    customer_type integer,
    assigned_staff integer,
    source character varying(255) COLLATE pg_catalog."default",
    employee_size integer,
    CONSTRAINT customer_enterprise_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer_lead
(
    id bigserial NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default",
    "position" character varying(255) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    date_of_birth character varying COLLATE pg_catalog."default",
    note character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT customer_lead_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_interest
(
    id bigserial NOT NULL,
    category character varying(255) COLLATE pg_catalog."default",
    productname character varying COLLATE pg_catalog."default",
    interest_status character varying(255) COLLATE pg_catalog."default",
    interest_start_date character varying COLLATE pg_catalog."default",
    note character varying(255) COLLATE pg_catalog."default",
    product_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT product_interest_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.customer_enterprise
    ADD CONSTRAINT fk_customer_contact FOREIGN KEY (customer_contact)
    REFERENCES public.customer_contact (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer_enterprise
    ADD CONSTRAINT fk_customer_lead FOREIGN KEY (customer_lead)
    REFERENCES public.customer_lead (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer_enterprise
    ADD CONSTRAINT fk_product FOREIGN KEY (product)
    REFERENCES public.product_interest (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;